remote_theme: pmarsceill/just-the-docs
title: Madajaju System Architectures
description: This is a list of architectures developed by madajaju. Including documentation and usage models.
google_analytics: G-SDCPXLJ9YG
